[tool.poetry]
name = "poetry update"
version = "0.1.0"
description = ""
authors = ["Albert <albert.minnibaeff@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
